# Generated by Django 5.2.4 on 2025-07-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
