# Generated by Django 5.2.4 on 2025-07-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_feedback_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='answer',
        ),
    ]
