# Generated by Django 5.2.4 on 2025-07-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_feedback_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
